nameOverride: openwebui

image:
  tag: v0.7.2

ingress:
  enabled: true
  class: {{#if DOMAIN}}shared-internet-facing-alb{{else}}internal-alb{{/if}}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  {{#if DOMAIN}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  host: openwebui.{{{DOMAIN}}}
  {{else}}
  host:
  {{/if}}

# openaiBaseApiUrl: https://litellm.{{{DOMAIN}}}/v1
openaiBaseApiUrl: http://litellm.litellm:4000/v1
openaiApiKey: {{{LITELLM_API_KEY}}}
extraEnvVars:
  - name: ENABLE_SIGNUP
    value: "false"
  - name: DEFAULT_USER_ROLE
    value: "pending"

ollama:
  enabled: false
pipelines:
  enabled: false

persistence:
  enabled: true
  size: 100Gi

resources:
  requests:
    cpu: 1 
    memory: 2Gi
  limits:
    memory: 2Gi
