FROM public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py310-sdk2.25.0-ubuntu22.04

COPY ./huggingface/hub/models--mistralai--Mistral-7B-Instruct-v0.3 /opt/vllm/huggingface-cache/Mistral-7B-Instruct-v0.3

COPY ./neuron/mistralai/Mistral-7B-Instruct-v0.3-int8 /opt/vllm/neuron-cache/Mistral-7B-Instruct-v0.3-int8