FROM public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py310-sdk2.25.0-ubuntu22.04

COPY ./huggingface/hub/models--meta-llama--Llama-3.1-8B-Instruct /opt/vllm/huggingface-cache/Llama-3.1-8B-Instruct

COPY ./neuron/meta-llama/Llama-3.1-8B-Instruct-int8 /opt/vllm/neuron-cache/Llama-3.1-8B-Instruct-int8