FROM public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py311-sdk2.26.0-ubuntu22.04

COPY ./huggingface/hub/models--Qwen--Qwen3-4B-Instruct-2507 /root/.cache/huggingface/hub/models--Qwen--Qwen3-4B-Instruct-2507

COPY ./neuron/Qwen/Qwen3-4B-Instruct-2507 /root/.cache/neuron/Qwen/Qwen3-4B-Instruct-2507