ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
{{#if DOMAIN}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
{{/if}}
  className: internet-facing-alb
  hosts:
{{#if DOMAIN}}
    - host: n8n.{{{DOMAIN}}}
      paths:
        - path: /
          pathType: Prefix
{{else}}
    - host: ""
      paths:
        - path: /
          pathType: Prefix
{{/if}}
  tls: []

main:
{{#unless DOMAIN}}
  config:
    n8n:
      secure_cookie: false
{{/unless}}
  persistence:
    enabled: true
    type: dynamic
    size: 10Gi
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      memory: 2Gi
